### ISSUE TITLE
Path Routing

### ISSUE THREAD

**Issue by smitraval24** [devyash2930/ShopSync-SE#6]
When access a page which do not exist then return to Page Not Found.

and when the user is not logged in then the user can not access the home page through URL

**Comment by vatsal-dp** [comment]
we should also auto route to home page after login.

**Comment by smitraval24** [comment]
for the page not found pop up is directly handled by the streamlit but the theme color changes each time a user tries to access the invalid URL.

**Comment by smitraval24** [comment]
Done the fix to maintain the same theme even after try to access the invalid URL. But there is another error the front screen of the account page.

**Comment by vatsal-dp** [comment]
error on refresh is now resolved
